package main

import (
	"bytes"
	"os"
	"os/exec"
	"testing"

	. "github.com/gregoryv/web"
)

func Test_generate_readme(t *testing.T) {
	out, err := exec.Command("go", "run", ".", "-h").CombinedOutput()
	if err != nil {
		t.Fatal(err)
	}
	// replace temporary build name
	from := bytes.Index(out, []byte("/tmp/"))
	to := bytes.Index(out, []byte("/cv"))
	res := append(out[:from], out[to+1:]...)

	data, err := os.ReadFile("example.yaml")

	page := NewPage(
		Html(
			Body(
				"<!-- Generated by main_test.go, DO NOT EDIT! -->",

				P(`cv - command for generating HTML from YAML`),
				Br(),

				Pre("$ cv -h\n", string(res)),

				H2("Template file format"),

				Pre(string(data)),
			),
		),
	)
	page.SaveAs("README.md")
}
