package main

import (
	"os/exec"
	"testing"

	. "github.com/gregoryv/web"
)

func Test_generate_readme(t *testing.T) {
	out, err := exec.Command("go", "run", ".", "-h").CombinedOutput()
	if err != nil {
		t.Fatal(err)
	}

	page := NewPage(
		Html(
			Body(
				P(`cv - command for generating HTML from YAML`),
				Br(),

				Pre("$ cv -h\n", string(out)),

				"<!-- Generated by main_test.go, DO NOT EDIT! -->",
			),
		),
	)
	page.SaveAs("README.md")
}
